import io

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv
import os
import re

from utils import extract_text_from_pdf
from prompts import PROMPT

# -----------------------------
# Load Environment Variables
# -----------------------------
def create_pdf(report):
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("<b><font size='20'>ResumeSense AI</font></b>", styles["Title"])
    )

    story.append(
        Paragraph("AI Resume Analysis Report", styles["Heading2"])
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    for line in report.split("\n"):

        line = line.strip()

        if not line:
            story.append(Paragraph("<br/>", styles["Normal"]))

        elif line.startswith("Overall ATS Score"):
            story.append(
                Paragraph(
                    f"<b><font size='15'>{line}</font></b>",
                    styles["Heading2"]
                )
            )

        elif (
            line.startswith("Matching Skills")
            or line.startswith("Missing Skills")
            or line.startswith("Strengths")
            or line.startswith("Suggestions")
        ):
            story.append(
                Paragraph(
                    f"<b><font color='blue'>{line}</font></b>",
                    styles["Heading2"]
                )
            )

        else:
            story.append(
                Paragraph(line, styles["Normal"])
            )

    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "<font size='9' color='grey'>Generated by ResumeSense AI</font>",
            styles["Normal"]
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer
load_dotenv()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=os.getenv("OPENROUTER_API_KEY"),
)

# -----------------------------
# Streamlit Page Config
# -----------------------------
st.set_page_config(
    page_title="ResumeSense AI",
    page_icon="📄",
    layout="wide"
)

# -----------------------------
# Header
# -----------------------------
st.title("🎯 ResumeSense AI")
st.caption("AI Powered ATS Resume Analyzer")

st.write(
    "Analyze your resume against any job description using AI and receive ATS-style feedback."
)

st.divider()

# -----------------------------
# Resume Upload
# -----------------------------
st.markdown("## 📄 Upload Resume")

uploaded_resume = st.file_uploader(
    "Upload Resume (PDF)",
    type=["pdf"]
)

# -----------------------------
# Job Description
# -----------------------------
st.markdown("## 💼 Job Description")

job_description = st.text_area(
    "Paste the Job Description",
    height=250,
    placeholder="Paste the complete job description here..."
)

# -----------------------------
# Analyze Button
# -----------------------------
if st.button("🚀 Analyze Resume"):

    if uploaded_resume is None:
        st.warning("⚠ Please upload your resume.")
        st.stop()

    if job_description.strip() == "":
        st.warning("⚠ Please paste the job description.")
        st.stop()

    with st.spinner("Analyzing Resume..."):

        resume_text = extract_text_from_pdf(uploaded_resume)

        final_prompt = f"""
{PROMPT}

RESUME:
{resume_text}

JOB DESCRIPTION:
{job_description}
"""

        try:

            response = client.chat.completions.create(
                model="deepseek/deepseek-chat",
                messages=[
                    {
                        "role": "user",
                        "content": final_prompt
                    }
                ]
            )

            result = response.choices[0].message.content

        except Exception as e:
            st.error(f"Error: {e}")
            st.stop()

    st.success("✅ Analysis Complete!")
    st.balloons()

    # -----------------------------
    # Extract ATS Score
    # -----------------------------
    score = None

    patterns = [
        r"ATS_SCORE:\s*(\d+)",
        r"Overall ATS Score:\s*(\d+)",
        r"Overall ATS Score:\s*\n\s*(\d+)"
    ]

    for pattern in patterns:
        match = re.search(pattern, result, re.IGNORECASE)
        if match:
            score = int(match.group(1))
            break

    if score is not None:

        st.markdown("## 📊 ATS Match Score")

        col1, col2 = st.columns([1, 3])

        with col1:
            st.metric("Score", f"{score}%")

        with col2:
            st.progress(score / 100)

    st.divider()

    # -----------------------------
    # Report
    # -----------------------------
    st.markdown("## 📄 Analysis Report")
    st.markdown(result)

    st.divider()

    # -----------------------------
    # Create PDF
    # -----------------------------
    pdf = create_pdf(result)

    # -----------------------------
    # Download Button
    # -----------------------------
    st.download_button(
        label="📄 Download PDF Report",
        data=pdf,
        file_name="ResumeSense_AI_Report.pdf",
        mime="application/pdf"
    )